name: Publish on NPM

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@lite-jsx/express"
          pull-request-header: ""
          commit-search-depth: 100

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
